### ISSUE TITLE
New constructor

### ISSUE THREAD

**Issue by fuCtor** [sufleR/sql_query#1]
Maybe make, some thing like this:

``` ruby
    def initialize(*attrs)
      fail 'options empty' if attrs.empty? || !attrs.last.is_a? Hash
      options = attrs.last
      case attrs[0]
      when String
        options[:sql_name] ||= name
      when Symbol
        options[:sql_name] ||= name
      end

      prepare_variables(options)
      @connection = ActiveRecord::Base.connection
    end
```

Use:

``` ruby
> query = SqlQuery.new(:get_player_by_email, email: 'e@mail.dev')
```

**Comment by sufleR** [comment]
Does this change fit your requirements?

https://github.com/sufleR/sql_query/commit/a7af8cf0175dea6795d712a4dcf5917ea146c493

Options hash may be empty. Not every query needs conditions.

I like idea for first argument as file name. 
with this change we can initialize SqlQuery with very similar way as we do with views

Example:

``` ruby
SqlQuery.new 'player/get_by_email', email: 'e@mail.dev'
```

**Comment by sufleR** [comment]
closing with release 0.2.0
