### ISSUE TITLE
prepare_for_logs reduces multiple spaces to single space in embedded parameters 

### ISSUE THREAD

**Issue by Barbez95** [sufleR/sql_query#15]
Hi! I've tried to upgrade to last released version 0.7.2, but the behaviour is still present.

The query template file "test_query.sql.erb" has the following content:
`SELECT * FROM my_table WHERE my_string_field = <%= quote @my_string_value %>`

Calling prepared_for_logs function
`SqlQuery.new('test_query', my_string_value: 'My   string   value').prepared_for_logs`

returns the following query
`"SELECT * FROM my_table WHERE my_string_field = 'My string value'"`
instead of 
`"SELECT * FROM my_table WHERE my_string_field = 'My   string   value'"`

**Comment by sufleR** [comment]
Hi @Barbez95 

I'm sorry for the late answer.
It seems that this behavior is from the beginning. 
I tried to figure it out but I don't see any easy-to-implement solution right now.

I'll experiment with regexp and if I will figure it out I will update gem.
If you know how to fix it please prepare PR. 
Thank you

**Comment by sufleR** [comment]
@Barbez95 I brute forced the query string to not replace multiple whitespaces inside quotation marks.

I added a test case for it and it seems to work fine.

Please review if this solution fixes your problem.

I think that it would be better if you would use ```execute(false)``` so prepared_for_logs wouldn't break your parameters.
It will be much safer in my opinion than trying to satisfy all quotations in query string.

**Comment by Barbez95** [comment]
Hi @sufleR,
I've opened a [PR](https://github.com/sufleR/sql_query/pull/17) with a different solution, let me know what do you think!
Thanks

**Comment by sufleR** [comment]
@Barbez95 changes merged and a new version of the gem was released.

Thank you very much for the PR.

**Comment by Barbez95** [comment]
@sufleR thank you!
