### ISSUE TITLE
Feature Request: Scopes & AR translations

### ISSUE THREAD

**Issue by naxels** [sufleR/sql_query#2]
Hi, love your gem!

really helps organizing SQL in files, and write advanced queries without the Active Record/Arel hassle

could you add Scopes implementation, so there is code reuse & chaining?
i now find myself copy/pasting the same WHERE's across queries.

and could you add Active Record 'translations'
like this example: .where(item: items)
is translated into = 'item', or IN ('item', 'item')
depending on whether you have a single param or Array as parameter.
now i have to do this: items.join(',') assuming the items Array already have ''s around the keys

Thank you!

**Comment by sufleR** [comment]
Hi @naxels 

For scopes impementation check latest code and try it in your app.
If it will fit your needs I will release new version of gem.

About 'translations' thing. I don't want to add such feature.
I think that you should have full control over data you are passing to sql templates.

If you really want to have such feature you can do it with partial right now.

```
# _in.sql.erb
IN (@your_array.join(','))
```

and use it whenever you need it but I don't recommend it. 

Readbility will suffer a lot imo and code will be longer than with `join(', ')` :).

**Comment by naxels** [comment]
Thank you for the quick reply!

I understand your point on 'translations'
and love the new Partials feature, really helps our team out

So far we've been making Partials for SELECT and WHERE pieces which we reuse all over now

Thanks!

**Comment by sufleR** [comment]
gem released so you may use version 0.3.0
