### ISSUE TITLE
Request: support option to use exec_query instead of execute?

### ISSUE THREAD

**Issue by timhwang21** [sufleR/sql_query#6]
Hello! I was wondering if it would be possible to support `exec_query` here instead of `execute`. This would be nice because `exec_query` returns an object that's easier to work with.

https://github.com/sufleR/sql_query/blob/master/lib/sql_query.rb#L27

If you think this is ok I can file a PR. Thanks! Proposed API would just be the addition of an `exec_query` method.

**Comment by sufleR** [comment]
@timhwang21 yes I accept PRs. Please write tests for it. Thank you.
